<div class="section section--default">
    <div class="container">
        <div class="grid">
            <div class="grid__12 grid__8@med">
                <span> <!-- content text must be in a wrapper if it's directly in a grid__item -->                  
                    <?php echo $block->dataValue('text');?>
                </span>
            </div>
        </div>
    </div>
</div>
